repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/meghprkh/godot-gdscript-toolkit/
    rev: 2e1c968d04f6e4b6e28217edb631720d079e2496
    hooks:
    - id: gdlint
    - id: gdformat
